### ISSUE TITLE
Iota does not support 'helpers' command.

### ISSUE THREAD

**Issue by Tobse101** [chrisoro/TXPromoter#1]
Installed everything I need with
`apt-get install python-pip -y && pip install --upgrade pip && pip install pyota`

Got error:

```
29.01.2018 16:32:06 | INFO | run finished. 5 more runs until reattach
29.01.2018 16:32:06 | INFO | found 12 tx in bundle. trying to promote/reattach
29.01.2018 16:32:10 | WARNING | Traceback (most recent call last):
  File "promoter.py", line 71, in promote
    promotable = api.helpers.is_promotable(tx.hash)
  File "/usr/local/lib/python2.7/dist-packages/iota/api.py", line 110, in __getattr__
    command = command,
InvalidCommand: Iota does not support 'helpers' command.

29.01.2018 16:32:10 | WARNING | Traceback (most recent call last):
  File "promoter.py", line 71, in promote
    promotable = api.helpers.is_promotable(tx.hash)
  File "/usr/local/lib/python2.7/dist-packages/iota/api.py", line 110, in __getattr__
    command = command,
InvalidCommand: Iota does not support 'helpers' command.
```

**Comment by chrisoro** [comment]
It seems like it is using an old pyota version since the helpers only got added in the most recent version.

Can you do pip list?

**Comment by Tobse101** [comment]
`Package              Version
-------------------- ---------
acme                 0.19.0
ansible              2.4.2.0
asn1crypto           0.22.0
certbot              0.19.0
certbot-nginx        0.19.0
certifi              2017.4.17
chardet              3.0.4
class-registry       2.1.2
ConfigArgParse       0.11.0
configobj            5.0.6
cryptography         1.9
dnspython            1.15.0
ecdsa                0.13
enum34               1.1.2
filters              1.3.2
funcsigs             0.4
httplib2             0.9.1
idna                 2.5
ipaddress            1.0.17
Jinja2               2.8
MarkupSafe           0.23
mock                 1.3.0
ndg-httpsclient      0.4.2
paramiko             1.16.0
parsedatetime        2.1
passlib              1.6.5
pbr                  1.8.0
pip                  9.0.1
psutil               5.0.1
py2casefold          1.0.1
pyasn1               0.1.9
pycrypto             2.6.1
PyICU                1.9.2
pyOpenSSL            17.3.0
PyOTA                2.0.3
pyparsing            2.0.3
pyRFC3339            1.0
pysha3               1.0.2
python-apt           1.1.0b1
python-dateutil      2.6.1
python2-pythondialog 3.3.0
pytz                 2014.10
PyYAML               3.11
regex                2018.1.10
requests             2.18.1
setuptools           33.1.1
six                  1.11.0
typing               3.6.2
urllib3              1.21.1
wheel                0.29.0
zope.component       4.2.2
zope.event           4.2.0
zope.hookable        4.0.4
zope.interface       4.1.3`

**Comment by Tobse101** [comment]
Installed again from source:

`git clone https://github.com/iotaledger/iota.lib.py.git`
`cd iota.lib.py/`
`pip install -e .`

worked for me 👍

**Comment by chrisoro** [comment]
Yup. As you can see it was as I suspected. You were running the PyOTA 2.0.3 instead of 2.0.4. This could be fixed by me having a proper setup.py but I'm no expert in that.

Anyway, it works no, so closing :)
